GET http://localhost:3000/products

###
GET http://localhost:3000/products/4

###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "product 1",
  "price": 100
}

###
PATCH http://localhost:3000/products/8
Content-Type: application/json

{
  "name": "product 4 updated",
  "price": 55
}

###
DELETE http://localhost:3000/products/3

###
GET http://localhost:3000/stock-inputs

###
GET http://localhost:3000/stock-inputs/1

###
POST http://localhost:3000/stock-inputs
Content-Type: application/json

{
  "product_id": 4,
  "quantity": 30,
  "date":"2000-01-01"
}